# Prometheus configuration for GitHub-Firebase Connector
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # GitHub-Firebase Connector application
  - job_name: 'github-firebase-connector'
    static_configs:
      - targets: ['github-firebase-connector:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Optional: Add other services here
  # - job_name: 'firestore-exporter'
  #   static_configs:
  #     - targets: ['firestore-exporter:9090']